-- Generated by scripts/generate-backfill-sql.js. Do not hand-edit.

INSERT INTO user_question_sets (user_id, set_id, subscribed_at)
   SELECT u.id, qs.id, '2026-09-19T18:26:40.470Z'
   FROM users u, question_sets qs
   WHERE qs.owner_user_id IS NULL
     AND NOT EXISTS (SELECT 1 FROM user_question_sets WHERE user_id = u.id AND set_id = qs.id);

UPDATE users SET streak_count = 0, streak_longest = 0, streak_last_active = NULL WHERE id = '085824f4-3aeb-4092-8466-3ec6780772fc';
